### ISSUE TITLE
Pagespeed Support for File Loading

### ISSUE THREAD

**Issue by ellisonpatterson** [Xon/XenForo-ViewStaffThreads#1]
Hey in case anyone else is using Pagespeed's LoadFromFile and this add-on causes errors to appear, use this:

`pagespeed LoadFromFileMatch "^https?://([^/]*)/data/avatar/([^/]*)/([^/]*)/([^?]*)" "/PATH_TO_XENFORO/data/avatars/\\3/\\4";`

And replace `PATH_TO_XENFORO` with the path to your XF installation.

**Comment by Xon** [comment]
That is a standard XenForo URL structure, nothing this add-on manipulates.

**Comment by ellisonpatterson** [comment]
Oh I meant to post this under https://github.com/Xon/XenForo-AvatarUrl.
